version: "3.9"
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:3000"
    environment:
      - NODE_ENV=production
      - DB_MONGO=mongodb://mongodb:27017/dummy
    depends_on:
      - mongodb

  frontend:
    build:
      context: ../dummy-react-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: